### PR TITLE
Add Crashlytics WebHook

### PR DESCRIPTION
**Pull request by edvakf**
Add support for [Crashlyticsh WebHook](ttps://dev.twitter.com/crashlytics/crash-reporting/web-hooks)

_73__idobata

### CODE REVIEW

**Comment by ursm** [comment]
Thank you for your contribution. We will test it after get invited to Crashlytics. Please wait a minute.

**Comment by edvakf** [comment]
Thanks. I've set the icon as `https://crashlytics.com/apple-touch-icon-crashlytics.png`, which I took from the `<link rel="apple-touch-icon-precomposed">` of the [login page](https://www.crashlytics.com/login), but please change if there is anything better.

**Comment by hibariya** [comment]
> but please change if there is anything better.

Okay, thanks.

And now, It worked well on our test environment. We'll deploy this to production as soon as we can :rocket:

**Comment by hibariya** [comment]
@edvakf Deployed to production. Thank you for your great works :whale:

**Pull request merged**
